### ISSUE TITLE
LTI loading messages

### ISSUE THREAD

**Issue by zmm** [moevm/mse_auto_checking_slides_vaganov#156]
НЕ понятно, это баг или просто отладочные сообщения, но изучить вопрос нужно

**Comment by HadronCollider** [comment]
Задача: http://e.moevm.info/mod/lti/view.php?id=1529

Описанное отладочное сообщение `Trying to get property of non-object` (из php от Moodle) возникает при использовании настройки External Tool задачи "Automatically based on tool URL" - точная причина неизвестна, однако при использовании `Preconfigured tool` (рекомендуемое подключение сконфигурированного инструмента к конкретной задаче) данное сообщение отсутствует (уже реализовано по ссылке выше)
