### ISSUE TITLE
Ошибки проверки, связанные с шаблоном

### ISSUE THREAD

**Issue by HadronCollider** [moevm/mse_auto_checking_slides_vaganov#227]
1. В [шаблоне ](https://docs.google.com/presentation/d/19lLrLoUcOrpjdUezDD4u0mmUdAXcErRczm8WCSYDHJs/edit#slide=id.p)нумерация есть, при этом система её не засчитывает. [Результат шаблона](http://slides-checker.moevm.info/results/61ee94e90d2d7ea8a427e659).
2. В [шаблоне ](https://docs.google.com/presentation/d/19lLrLoUcOrpjdUezDD4u0mmUdAXcErRczm8WCSYDHJs/edit#slide=id.p)8 слайдов, в итоге не проходит проверку. (_это про настройки диапазона_)

**Comment by zmm** [comment]
Я бы задачу расширил до "пофиксить систему и/или шаблон так, чтобы шаблон проходил формальные рповерки (которые и должен пройти)". Доступ к шаблону дал.

**Comment by HadronCollider** [comment]
- [X] В шаблоне нумерация есть, при этом система её не засчитывает
    - [X] Для PPTX/PPT - исправлено (в файлах данного формата может использоваться спец строка `<#>` для указания автоматического подсчета номера слайда, вместе текста с числов) 
        - http://slides-checker.moevm.info/check_list
    - [ ] Для ODP-формата определение трудноосуществимо - номер содержится в тексте страницы (если только костылить)
        - http://slides-checker.moevm.info/check_list
