### ISSUE TITLE
Ошибки на странице результата

### ISSUE THREAD

**Issue by HadronCollider** [moevm/mse_auto_checking_slides_vaganov#228]
1. Неверная нумерация/соответствие названия/вывода для старых проверок (захардкоржены -> отображаются не проводимые проверки + смещены при добавлении новой проверки)
2. Неработающий предпросмотр 
    - ![image](https://user-images.githubusercontent.com/21632402/161654695-46dc67a3-cd5b-4ee4-8574-22432dfdfa40.png)
    - Примечание: очень похоже на ошибку либы (???)
3. Время проверок по гринвичу

**Comment by zmm** [comment]
2 Надо убедится, что у нас зафиксированы версии библиотек
3 Нужно пробросить с хоста файл, отвечающий за таймзону - уточните у Ярослава, как это правильно сделать

**Comment by HadronCollider** [comment]
- [X]  Неверная нумерация/соответствие названия/вывода для старых проверок
    - Исправлен маппинг критериев и результатов
- [X] Неработающий предпросмотр
    - Обновлена JS-библиотека 
- [ ] Время проверок по гринвичу - to #241
