### ISSUE TITLE
Гибкость проверок (с анализом текста)

### ISSUE THREAD

**Issue by HadronCollider** [moevm/mse_auto_checking_slides_vaganov#230]
1. **Запасные слайды** Запасные файлы считаются с момента встречи “Запасные файлы”. В [требованиях](http://se.moevm.info/doku.php/diplomants:start:slides_checklist_etu) это не сказано, там указано ““запасных” слайдов, расположенных после слайда “Заключение”", при этом в [шаблоне ](https://docs.google.com/presentation/d/19lLrLoUcOrpjdUezDD4u0mmUdAXcErRczm8WCSYDHJs/edit#slide=id.p)апробация идёт после заключения. Тут тогда нужно явно указать, что для обозначения окончания основных слайдов требуется добавить слайд с заголовком “Запасные слайды”, т.к. другие вариации (“Запасной слайд 1”, “Запасной слайд (1)”, “Запасные слайды текст” и т.д.) не учитываются.
2. **Заголовки не более двух строк** Система считает строку при явном переносе строки. Если перенос был выполнен автоматически (в строке слишком много символов), то такой перенос не засчитывается как смена строки.
3. **Актуальность** В [требованиях](http://se.moevm.info/doku.php/diplomants:start:slides_checklist_etu) есть уточнение “в начале”, проверки на это нет.
Прохождение проверки = наличие слова “актуальность”. Добавить склонения (актуальностИ, актуальностЬЮ) и другие части речи (актуально, актуальный и их склонения)?

**Comment by zmm** [comment]
1. Поправил правила, в приложении нужно  добавить явное уточнение - как мы считаем запасные слайды.
2. Надо попробовать пофиксить, если быстро не выйдет - вынести отдельно в баклог
3. Предлагаю пока просто использовать список склонений, полноценный nlp отдельная задача

**Comment by HadronCollider** [comment]
- [X] Запасные слайды
    - В результат проверки добавляется сообщение `Проверьте, что запасные слайды расположенны после слайда с заголовком “Запасные слайды”`
- [ ] Заголовки не более двух строк to #240 
- [X] Актуальность
    - Добавлены склонения
