### ISSUE TITLE
опциональная отправка двух файлов

### ISSUE THREAD

**Issue by zmm** [moevm/mse_auto_checking_slides_vaganov#290]
в ряде случаев бывает нужно загрузить и исходник, и pdf

**Comment by HadronCollider** [comment]
Класс пользователя - https://github.com/moevm/mse_auto_checking_slides_vaganov/blob/f6bf8e362d6b4ad7d09837b4f0c9446b2c33e960/app/db/db_types.py#L19

**Comment by HadronCollider** [comment]
Авторизация и запись данных в пользователя - https://github.com/moevm/mse_auto_checking_slides_vaganov/blob/master/app/server.py#L60
