### ISSUE TITLE
Повышение качества отображения и конвертации в pdf

### ISSUE THREAD

**Issue by zmm** [moevm/mse_auto_checking_slides_vaganov#309]
У многих студентов проблемы с тем что едет верстка после конвертации, нет шрифтов и тд - надо изучить потенциальные решения

**Comment by HadronCollider** [comment]
Вместо unoconv можно использовать libreoffice (уже применяется в анализе документов)
https://github.com/moevm/mse_auto_checking_slides_vaganov/blob/c7c8de2e32f844133cfe12fa120be5d84ec1fc64/app/main/mse22/converter_to_docx/converter.py#L15

**Comment by HadronCollider** [comment]
Добавлено в #317, ещё не развернуто 
https://github.com/moevm/mse_auto_checking_slides_vaganov/blob/e7abcc27a25c5fefabefa5db8bd82b8c3792b959/app/utils/converter.py#L17
