### ISSUE TITLE
Проверка орфографии в рамках проверок ВКР

### ISSUE THREAD

**Issue by zmm** [moevm/mse_auto_checking_slides_vaganov#358]
Эта задача пока для сбора ссылок
https://github.com/languagetool-org/languagetool
https://languagetool.org/

**Comment by Saprigenie** [comment]
Есть несколько хороших библиотек, которые могут проверять орфографию (расставлены в соответствии с субъективной оценкой):
1) Уже представленный LanguageTool (https://github.com/languagetool-org/languagetool) - существует хорошая библиотека под Python, которая запускает локальный сервер библиотеки на Java и обращается к ней через Python (https://pypi.org/project/language-tool-python/#description). Показывает отличный результат по поиску орфографических ошибок. Может легко использоваться для поиска их количества и возможных исправлений. Из минусов - необходима установки Java в контейнере и первичное скачивание 220 Мб приложения LanguageTool на Java при первом использовании библиотеки. Однако по возможности внедрения и результатам поиска русских орфографических ошибок превосходит конкурентов.
2) Pyenchant (https://pyenchant.github.io/pyenchant/) - изначально нет проверки русской орфографии, но есть возможность использования пакета русского языка из Libre office (или можно воспользоваться другими словарями русского, например: https://code.google.com/archive/p/hunspell-ru/). Может проверять слова и целые предложения, использовать фильтры на email, ссылки и т.д.
3) JamSpell (https://github.com/bakwc/JamSpell) - проверка орфографии на основе языковых моделей довольно быстрая и точная в поиске исправлений. Существует предобученный русский вариант, можно обучить свой. Но функциональность крайне ограниченная.
4) TextBlob (https://textblob.readthedocs.io/en/dev/) - построена на библиотеке nltk, но может решать не совсем нужную задачу - коррекция текста. Для русского языка придется обучить на русских текстах (пример обучения: https://stackabuse.com/spelling-correction-in-python-with-textblob/). Встроенных в библиотеку решений для русского нет.
5) PySpellChecker (https://pyspellchecker.readthedocs.io/en/latest/index.html) - довольно простая библиотека, специализирующаяся на проверке орфографии. Имеет русский язык по умолчанию. Работает только со словами, либо списками слов (нужна правильная токенизация перед запуском).
