### ISSUE TITLE
Информационная страница о наборе критериев 

### ISSUE THREAD

**Issue by HadronCollider** [moevm/mse_auto_checking_slides_vaganov#373]
- какие критерии входят в набор
- за что отвечают критерии

**Comment by MarinaProsche** [comment]
Первый вариант страницы

https://github.com/moevm/mse_auto_checking_slides_vaganov/tree/373_page_with_criteria

**Comment by MarinaProsche** [comment]
https://github.com/moevm/mse_auto_checking_slides_vaganov/pull/460/commits/9e1d8d5e62d63c8fea6723155f6b215e50a859bd

Первый приблизительный вариант таблицы с информацией.
