### ISSUE TITLE
Визуализировать максимальный объем файла при загрузке

### ISSUE THREAD

**Issue by zmm** [moevm/mse_auto_checking_slides_vaganov#424]

**Comment by MarinaProsche** [comment]
https://github.com/moevm/mse_auto_checking_slides_vaganov/pull/436

Изменен файл "upload.html", добавлена информация о том, что максимальный объем загружаемого файла не должен превышать 16 мб ( {{config.MAX_CONTENT_LENGTH}} ). В итоге фразы в формах загрузки изменены на:
pptx: "Формат: {{ ", ".join(formats) }}, объем не больше {{config.MAX_CONTENT_LENGTH}} Mб." 
pdf: "Формат: pdf, объем не больше {{config.MAX_CONTENT_LENGTH}} Mб."

**Comment by MarinaProsche** [comment]
Изменен файл "upload.html", добавлена информация о том, что максимальный объем загружаемого файла не должен превышать 16 мб ( {{config.MAX_CONTENT_LENGTH}} ). В итоге фразы в формах загрузки изменены на:
Форматы: {{ ", ".join(formats) }} (объем не больше {{ config.MAX_CONTENT_LENGTH//1024//1024 }} Mб.) 
Формат: pdf (объем не больше {{ config.MAX_CONTENT_LENGTH//1024//1024 }} Mб.)
