### ISSUE TITLE
Критерий отчет - количество источников (мин и макс пороги)

### ISSUE THREAD

**Issue by zmm** [moevm/mse_auto_checking_slides_vaganov#426]
Нужно сделать параметризированный критерий (оба порога - параметры) + необходимо переиспользовать существующие наработки по поиску источников

**Comment by zmm** [comment]
для дипломников 24 года - настроить


Магистры : 

Количество ссылок на литературу должно быть представительным (не менее 25 источников), список источников не должен состоять исключительно из ссылок на интернет ресурсы. 

Бакалавры:
Количество ссылок на литературу должно быть представительным (не менее 10 источников, желательно 15), список источников не должен состоять исключительно из ссылок на интернет ресурсы.

**Comment by MarinaProsche** [comment]
Добавлен кретерий-параметр количества литературы (минимальный и максимальный)
Реализуется после проверки существующего списка источников на другие ошибки.
Изменения сделаны в уже существующем файле "literature_references"

https://github.com/moevm/mse_auto_checking_slides_vaganov/tree/426_min_and_max_lit_references
