### ISSUE TITLE
Отображению пользователю ошибок системы (storage overload)

### ISSUE THREAD

**Issue by HadronCollider** [moevm/mse_auto_checking_slides_vaganov#430]
Сейчас в случае переполнения в ответ на запрос возвращается строка (которая к тому же не обрабатывается на клиенте)
https://github.com/moevm/mse_auto_checking_slides_vaganov/blob/15c583eb50d77979ef0a0a08542d04d69884f1d8/app/server.py#L174

**Comment by MarinaProsche** [comment]
https://github.com/moevm/mse_auto_checking_slides_vaganov/pull/439

Исправлен файл assets/scripts/upload.js
Выводится сообщение об ошибке с заданным текстом (allert)
