### ISSUE TITLE
Критерий слайды - пустые слайды

### ISSUE THREAD

**Issue by zmm** [moevm/mse_auto_checking_slides_vaganov#432]
Проверять, что в презентации нет совсем пустых слайдов или слайдов, состоящих только из заголовков

**Comment by MarinaProsche** [comment]
Добавлен критерий проверки пустых слайдов в презентации. Файл "empty_slide_check".
Ответ реализован в виде страниц-ссылок на пустые слайды.

https://github.com/moevm/mse_auto_checking_slides_vaganov/tree/432_empty_slide
