### ISSUE TITLE
Кастомизация сообщения об ошибке, когда загружаемый материал больше чем максимально разрешенный объем

### ISSUE THREAD

**Issue by zmm** [moevm/mse_auto_checking_slides_vaganov#435]
Нужно модифицировать сообщение таким образом:

"Объем загружаемого вами документа ИМЯ_ФАЙЛА превышает максимально разрешенный объем ВЕЛИЧИНА_МАКС_ОБЪЕМА МБ. Для уменьшения объема файла, мы рекомендуем следующие действия:
- общее - снизить разрешение изображений,
- для презентаций - временно убрать дополнительные слайды.
"

**Comment by MarinaProsche** [comment]
https://github.com/moevm/mse_auto_checking_slides_vaganov/pull/439

Исправлен файл assets/scripts/upload.js
Выводится сообщение об ошибке с заданным текстом (allert)
