### ISSUE TITLE
Ссылки на все работы автора на странице отдельной проверки

### ISSUE THREAD

**Issue by zmm** [moevm/mse_auto_checking_slides_vaganov#437]
Нужно добавить две ссылки на страницу /results/*
- ссылка на общий список отправок этого пользователя
- ссылка на список отправок этого пользователя для текущего Criteria

**Comment by MarinaProsche** [comment]
https://github.com/moevm/mse_auto_checking_slides_vaganov/tree/437_links_for_results_html

Добавлено две ссылки в файле "results.html" внизу страницы согласно заданию.
