### ISSUE TITLE
Условный критерий (для слайдов)  -если есть ссылка на гитхаб или его аналоги, проверить что она не 404

### ISSUE THREAD

**Issue by zmm** [moevm/mse_auto_checking_slides_vaganov#444]
если есть ссылка или упоминания репо

**Comment by MarinaProsche** [comment]
https://github.com/moevm/mse_auto_checking_slides_vaganov/tree/444_verify_git_link
Первый вариант проверки слайдов на корректность репозиториев.

Реализованы:

в слайде "Апробация"
Поиск репозиториев github, gitlab, bitbucket.
Поиск некорректных выражений вместо ссылок, например "(github)" или "gitlab"
Отсутствие ссылок при упоминании репозитория .

Во всем проекте:
Репозитории "github" проверяются на существование, пустоту (парсингом), и на приватность.
Репозитории "gitlab" проверяются на существование и приватность.
Репозитории "bitbucket" проверяются на существование, из проверки на приватность исключены, поскольку недоступны в России.

Сейчас для проверки репозитория "gitlab" использован личный токен, нужна консультация, как подкорректировать.
Для более четкой проверки всех репозиториев на пустоту было решено использовать отдельную проверку.

**Comment by HadronCollider** [comment]
Добавить в PresVerifyGitLinkCheck параметр "deep_check (bool)"
- если False (по умолчанию) - осуществлять "простую" проверку - что код возврата ссылок = 200 (иначе - в список некорректных)
- если True - логика с глубокой проверкой репозиториев - данный код желательно вынести в отдельный метод для возможного дальнейшего расширения (проверка кол-ва коммитов / их историю и пр.)
