### ISSUE TITLE
Экспорт ZIP. Оригинальные имена файлов как параметр

### ISSUE THREAD

**Issue by HadronCollider** [moevm/mse_auto_checking_slides_vaganov#453]
https://github.com/moevm/mse_auto_checking_slides_vaganov/blob/43f4b093016cdae03cf40e2d1a3556444e65b514/app/server.py#L510
- экспорт выглядит как файлы `[check_id].pptx`

**Comment by zmm** [comment]
Нужно добавить к запросу параметр (/get_zip?original_names=true), если он true, то вместо [check_id].pptx сохраняем оригинальные имена файлов (какими они были при загрузке в систему)

**Comment by MarinaProsche** [comment]
https://github.com/moevm/mse_auto_checking_slides_vaganov/pull/474/commits/1dc9a75ff009a8d81565e1936cf9a61ef8fd0d4e
Вариант выполнения
