### ISSUE TITLE
Добавить в github actions проверку на наличие конфликтов

### ISSUE THREAD

**Issue by zmm** [moevm/mse_auto_checking_slides_vaganov#472]
Сейчас наши скрипты непрерывной интеграции собраны в файле https://github.com/moevm/mse_auto_checking_slides_vaganov/blob/master/.github/workflows/build.yml

Нужно добавить еще одним файлом вот такую проверку, которая позволит нам автоматически маркировать Pr, где есть конфликты

https://github.com/marketplace/actions/auto-label-merge-conflicts

**Comment by MarinaProsche** [comment]
https://github.com/moevm/mse_auto_checking_slides_vaganov/pull/475/commits/357685ba6ee32fe1bb16373b800c89c9024e3f59
Вариант проверки
