### ISSUE TITLE
Страница /version

### ISSUE THREAD

**Issue by zmm** [moevm/mse_auto_checking_slides_vaganov#84]
По аналогии с https://github.com/OSLL/web_speech_trainer/issues/14

**Comment by kinekt2000** [comment]
Файл с данными о версии генерировать в скрипте act.sh?

**Comment by HadronCollider** [comment]
@kinekt2000 
Данные о версии должны генерироваться в https://github.com/moevm/mse_auto_checking_slides_vaganov/blob/dev/scripts/restart.sh при развертывании системы (гита внутри контейнера с системой, где запускается `act.sh` нет)

**Comment by kinekt2000** [comment]
Понял, а в где хранить этот файл? Я так понимаю, он должен сгенерироваться, а затем поместиться в образ, откуда к нему будет иметь доступ приложение в контейнере.

**Comment by HadronCollider** [comment]
Можно хранить его в корневом каталоге (главное знать к нему путь в приложении, чтобы загружать из него информацию для отображения на странице)

**Comment by kinekt2000** [comment]
А как должна выглядеть страница, подцеплять ее к каким-нибудь уже готовым шаблонам, или ссылки на ней какие сделать?
Может есть какой-то макет или хотя б на пальцах объяснить?
И еще микровопрос, надо ли делать проверку на админа по этому запросу?

**Comment by kinekt2000** [comment]
Я тут немного завис. Заголовок рендерится только если ему передать юзернейм. На данный роут я не ставлю `@login_required`, а значит юзернейма у меня нет, а значит заголовок срендерить не могу. Поэтому либо оставляю голую страницу с таблицей, либо делаю там дополнительно ссылку где-нибудь.

**Comment by HadronCollider** [comment]
Значит делаем без хедера, дополнительные ссылки на /version добавлять не нужно, но открываться страница /version должна в новом вкладке (настройка тега `<a>` для ссылки, показываемой админу)

**Comment by kinekt2000** [comment]
А это нормально, что вебпак уже на полмегабайта бандл собирает? Грузить весь код ради одной, не самой важной странички, может быть нерационально.

**Comment by HadronCollider** [comment]
Сам подход расположить весь js в одном файле - не лучшая идея, но теперь вся система на этом стоит и менять что-то сложно.

По поводу загрузки кода - он кэшируется в браузере, поэтому это не столь критично

**Comment by kinekt2000** [comment]
Такой внешний вид сойдет?

Если файл подгрузился нормально и без проблем
![image](https://user-images.githubusercontent.com/42917151/123267459-b4372e00-d505-11eb-8961-b786f0107d36.png)

Если не получилось распарсить
![image](https://user-images.githubusercontent.com/42917151/123267637-e9438080-d505-11eb-997e-78c8823e2d73.png)

Если проблемы с открытием файла
![image](https://user-images.githubusercontent.com/42917151/123267776-0d06c680-d506-11eb-8b27-5e94c03186d1.png)

**Comment by HadronCollider** [comment]
Внешний вид - ок, разве что при проблеме открытия лучше писать "No <version_file_path"

**Comment by kinekt2000** [comment]
![image](https://user-images.githubusercontent.com/42917151/123273805-a1275c80-d50b-11eb-9730-65186e0e34c2.png)

![image](https://user-images.githubusercontent.com/42917151/123273928-ba300d80-d50b-11eb-9f7b-d76cb2273162.png)
