### ISSUE TITLE
Доп. фичи https://github.com/moevm/mse_auto_checking_slides_vaganov/issues/80

### ISSUE THREAD

**Issue by zmm** [moevm/mse_auto_checking_slides_vaganov#85]
На странице добавить:
- возможность сортировать по колонкам
- фильтры в колонках (фильтры сохраняются в адресную строку)
- пагинация
- колонка для названия презентации

**Comment by kinekt2000** [comment]
Как я могу получить название презентации по ее id в записи пользователя?
И можно ли где-то взять уже заполненную БД и вставить ее в контейнер, чтоб не заполнять вручную?

**Comment by kinekt2000** [comment]
Есть вариант создать функцию
```python
def paginate(collection, page, limit) -> dict
```
Которая вернет словарь:
```python
{
    prev = {
        page: int,
        limit: int
    },
    next = {
        page: int,
        limit: int
    },
    data = [
        record1, record2, ...
    ]
}
```

Такую функцию можно будет использовать для любой уже отфильтрованной коллекции, чтоб получить страницы.
Если вариант подходит, то где разместить?

**Comment by HadronCollider** [comment]
@kinekt2000

Необходимости в кастомной пагинации нет
(по примерам из других проектов)

Фильтрация/пагинация возможна средствами mongo (в примере используется движок, но sort/skip/limit - встроенные средства mongo)
```python3
def get_filter_logs(self, query={}, limit=None, offset=None, sort=None, order=None):
        logs = Logs.objects.raw(query).order_by([('time', DESCENDING)])
        count = logs.count()
        if limit is not None and offset is not None:
            logs = logs.skip(offset).limit(limit)
        if sort:
            if order == "asc":
                logs = logs.order_by([(sort, ASCENDING)])
            else:
                logs = logs.order_by([(sort, DESCENDING)])
        return logs, count
```

Данные для фильтрации с клиента можно получать с помощью bootstrap-таблиц (есть встроенные методы, вызываемые при/для фильтрации, https://bootstrap-table.com/docs/extensions/filter-control/).
```js
    <table id="logs_table" class="table table-sm" style="width: 100%" 
    data-toggle="table" 
    data-show-fullscreen="true"
    data-filter-control="true" 
    data-pagination="true" 
    data-show-search-clear-button="true"
    data-page-list="[5, 10, 25, 50, All]" 
    data-detail-view="true" 
    data-detail-formatter="detailFormatter"
    data-ajax="ajaxRequest"
    data-query-params="queryParams"
    data-show-refresh="true"
    data-auto-refresh="true"
    data-auto-refresh-interval="10"
    data-side-pagination="server">
        <thead>
            <tr>
                <th scope="col" class="log_id" data-field="_id" data-formatter="LogLink">id</th>
                <th scope="col" data-field="time" data-filter-control="datepicker" data-filter-datepicker-options='{"autoclose":true, "clearBtn": true, "todayHighlight": true, "format": "yyyy-mm-dd"}' data-sortable="true">time</th>
                <th scope="col" data-field="pathname" data-filter-control="select" data-sortable="true">pathname</th>
                <th scope="col" data-field="lineno" data-sortable="true">lineno</th>
                <th scope="col" data-field="levelname" data-filter-control="select" data-sortable="true">levelname</th>
                <th scope="col" data-field="message" data-formatter="MsgFormatter" class="msg" data-filter-control="input" data-sortable="true">message</th>
            </tr>
        </thead>
    </table>
```

**Comment by kinekt2000** [comment]
@HadronCollider 
Есть уже заполненная БД? Если да, то где ее взять и как установить себе?

**Comment by HadronCollider** [comment]
БД нет, но нескольких проверок презентаций для создания записи решений в бд вполне хватит для проверки

**Comment by futurewarning** [comment]
> Как я могу получить название презентации по ее id в записи пользователя?
https://github.com/moevm/mse_auto_checking_slides_vaganov/blob/bfa16b1bbc397a60828d7ef2e62950960e1ca988/app/bd_helper/bd_helper.py#L187, `finename = pr_obj['name']` для получения названия файла

**Comment by kinekt2000** [comment]
@HadronCollider 
По большей части с фронтом закончил, таблицу, пагинацию, фильтры, сортировку сделал, все это отображается в адресной строке.
Сейчас проблемы с бэком. Данные, которые отображаются в этой таблице, находятся в разных коллекциях. Как мне все это объединить, чтоб использовать методы find(...), skip(...), limit(...) и т.д.

**Comment by HadronCollider** [comment]
@kinekt2000 
Разумнее, кажется, добавить необходимые поля (пользователь + название презентации) в модель Checks, поскольку зависимость от других коллекций только усложняет работу.
https://github.com/moevm/mse_auto_checking_slides_vaganov/blob/79c04e1b3c36f52d50afacdec70df34cfd41fe45/app/bd_helper/bd_types.py#L67
При создании записи проверки можно передавать и указывать эти поля
https://github.com/moevm/mse_auto_checking_slides_vaganov/blob/20964cd4042e1e5299d6883faf94da7ffba35e44/app/bd_helper/bd_helper.py#L128-L131

Можно было бы использовать агрегацию для объединения информации и дальнейших find/skip/limit, но это ресурсоемкие операции+костыли. 

P.S. Модель БД изначально была не идеальна - теперь меняем её в процессе

**Comment by kinekt2000** [comment]
По поводу добавления полей в монгу налету, файл db-scheme.jsd никак менять не надо?
Также я попытался как-то еще поковырять bootstrap-table, возникли некоторые сложности с созданием кастомных фильтров. Хотел сделать фильтры для ввода диапазона дат и диапазона для значений результатов. В итоге сделал, но далеко не идеальным способом, если у кого-то есть опыт создания такого или хотя бы найдутся примеры, буду безмерно благодарен. Сам ничего толком найти не смог, а документация дрянная до безобразия.

**Comment by kinekt2000** [comment]
В таблице должны быть:
* id
* название
* логин
* дата добавления
* дата проверки
* дата загрузки на мудл
* результат

Я посмотрел, что находится в Checks
https://github.com/moevm/mse_auto_checking_slides_vaganov/blob/20964cd4042e1e5299d6883faf94da7ffba35e44/app/bd_helper/bd_types.py#L67-L80
Я даже не знаю, какие именно поля мне нужны, тут вроде вообще никаких дат нет. Вижу только conclusion, который, как я понимаю, - результат. Если даже и добавлю пользователя и название презентации в модель, то что делать с этими датами я совсем ума не приложу.

**Comment by futurewarning** [comment]
> В таблице должны быть:

https://github.com/moevm/mse_auto_checking_slides_vaganov/blob/20964cd4042e1e5299d6883faf94da7ffba35e44/app/bd_helper/bd_helper.py#L191 - здесь дата

> Вижу только conclusion, который, как я понимаю, - результат.

Это (один из) критериев проверок, результат в дев сейчас выглядит как 
https://github.com/moevm/mse_auto_checking_slides_vaganov/blob/20964cd4042e1e5299d6883faf94da7ffba35e44/app/bd_helper/bd_helper.py#L193
на самом деле он должен выглядеть так
https://github.com/moevm/mse_auto_checking_slides_vaganov/blob/cad4f487f324c8c92f9d22536841cd223b84fd9c/app/bd_helper/bd_helper.py#L212 (учитывая https://github.com/moevm/mse_auto_checking_slides_vaganov/issues/106)

**Comment by HadronCollider** [comment]
Добавить поля
- пользователь
- презентация
- score

**Comment by kinekt2000** [comment]
@HadronCollider 
Начал вводить таблицу в проект и столкнулся с проблемой.  После минификации вебпаком происходят странные дела. JS функции, которые непосредственно не используются кодом не проходят через babel и минификацию, а значит не могут вызваться на странице, например для ajax запроса.
Как вариант могу затолкать, весь этот скрипт в html тэг `script`.

**Comment by HadronCollider** [comment]
@kinekt2000 
А вы уверены, что минификация происходит?

Скажу сразу, что при использовании томов и, соответственно, `docker-compose-dev` файл `all.min.js`, которые формируются на этапе сборки: https://github.com/moevm/mse_auto_checking_slides_vaganov/blob/f995fcb34e2aa58a6b2d53d163cbf52dbd8ec35f/Dockerfile#L19
"затирается", после того как рабочая директория с хоста передается в контейнер (эти файлы есть в образе, но при запуске контейнера мы заменяем папку).

В качестве решения - можно подключиться к уже запущенному контейнеру и выполнить команду `./act.sh -b` вручную, перезапустить контейнер и наслаждаться новый all.min.js

**Comment by kinekt2000** [comment]
Сам себе проблему придумал, сам решил. Вообще да, после вебпака невозможно вызвать какую-нибудь функцию из html, их просто не видно.
Решение простое: эти функции можно добавить к необходимым событиям через js.

**Comment by kinekt2000** [comment]
А почему задача не закрылась?

**Comment by HadronCollider** [comment]
Задача чувствует, что исполнитель недостаточно помучался
