### ISSUE TITLE
Флажок .env для отключения страницы регистрации 

### ISSUE THREAD

**Issue by zmm** [moevm/mse_auto_checking_slides_vaganov#98]
Делаем и сам флажок и механизм включения / выключения страницы

**Comment by kinekt2000** [comment]
Механизм отключения страницы можно реализовать через декоратор
```python
def condition(decorator, condition):
    if not condition:
        def inner(func):
            def wrapper(*args, **kwargs):
                return func(*args, **kwargs)
            return wrapper
        return inner
    return decorator
```

Пример использования
```python

SIGNUP_PAGE_ENABLED = os.environ.get("SIGNUP_PAGE_ENABLED", False)

@condition(app.route("/signup", methods=["GET", "POST"]), SIGNUP_PAGE_ENABLED)
def signup():
    # handle request
    pass
```

В таком случае сервер не будет ничего знать о запросах, для которых условие ложно.

Если такой вариант подходит, то где его разместить?

**Comment by HadronCollider** [comment]
@kinekt2000 

Получение переменной из окружения лучше делать в settings.py, аналогично
https://github.com/moevm/mse_auto_checking_slides_vaganov/blob/bfa16b1bbc397a60828d7ef2e62950960e1ca988/app/settings.py#L15
Потом эта переменная будет доступна в конфиге приложения через app.config
https://github.com/moevm/mse_auto_checking_slides_vaganov/blob/bfa16b1bbc397a60828d7ef2e62950960e1ca988/app/server.py#L34

Идея с декоратором - подходит (инстанс приложения с конфигом можно получать `from flask import current_app`).
Размещение - в app/utils/decorators.py
